---
- name: Ansible playbook to dockerize and run yolo e-commerce app using ansible
  hosts: all
  become: true
  roles: 
    - docker-installation
    - docker-compose-installation
    - setup-nodejs
    - setup-npm 
    - setup-mongodb 
    - backend-deployment
    - frontend-deployment
    