#SPDX-License-Identifier: MIT-0
---
# tasks file for setup-nodejs
---
- name: Add NodeSource APT repo
  shell: curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  args:
    executable: /bin/bash

- name: Install Node.js
  apt:
    name: nodejs
    state: present
